### ISSUE TITLE
Test failures ...

### ISSUE THREAD

**Issue by roboweaver** [andrew-templeton/cfn-lambda#12]
Getting 7 test failures on project when running "npm test" (not familiar enough with the test harness to know if these are problem or not).

```
75 passing (4s)
  7 failing

  1) SDKAlias Param Manipulation should force booleans along the forceBools path sets:
     TypeError: Cannot read property 'Long' of undefined
      at src/SDKAlias.js:9:8269
      at Array.reduce (native)
      at src/SDKAlias.js:9:8048
      at Array.forEach (native)
      at forcePaths (src/SDKAlias.js:9:7779)
      at forceBoolean (src/SDKAlias.js:9:9943)
      at usableParams (src/SDKAlias.js:9:4208)
      at SimpleAlias (src/SDKAlias.js:9:1871)
      at src/SDKAlias.js:9:930
      at Context.<anonymous> (test/sdk.alias.js:172:7)

  2) SDKAlias Param Manipulation should force numbers along the forceNums path sets:
     TypeError: Cannot read property 'Long' of undefined
      at src/SDKAlias.js:9:8269
      at Array.reduce (native)
      at src/SDKAlias.js:9:8048
      at Array.forEach (native)
      at forcePaths (src/SDKAlias.js:9:7779)
      at forceNum (src/SDKAlias.js:9:9547)
      at usableParams (src/SDKAlias.js:9:4582)
      at SimpleAlias (src/SDKAlias.js:9:1871)
      at src/SDKAlias.js:9:930
      at Context.<anonymous> (test/sdk.alias.js:229:7)

  3) SDKAlias Physical ID Generation should work with string mappable physicalId with no returned values:
     TypeError: Cannot read property 'UseMeAsId' of undefined
      at src/SDKAlias.js:9:7636
      at src/SDKAlias.js:9:2802
      at Object.test (test/sdk.alias.js:429:13)
      at SimpleAlias (src/SDKAlias.js:9:2370)
      at src/SDKAlias.js:9:625
      at Context.<anonymous> (test/sdk.alias.js:438:7)

  4) Update Should work with unchanged PhysicalResourceId:
     Uncaught TypeError: Cannot convert undefined or null to object
      at Function.keys (<anonymous>)
      at JSONDeepEquals (src/JSONDeepEquals.js:9:460)
      at CfnLambda (index.js:9:10486)
      at test/update.js:42:7
      at Server.<anonymous> (test-helpers/https/server.js:9:1794)
      at emitListeningNT (net.js:1288:10)
      at _combinedTickCallback (internal/process/next_tick.js:71:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  5) Update Should work with a provided PhysicalResourceId:
     Uncaught TypeError: Cannot convert undefined or null to object
      at Function.keys (<anonymous>)
      at JSONDeepEquals (src/JSONDeepEquals.js:9:460)
      at CfnLambda (index.js:9:10486)
      at test/update.js:67:7
      at Server.<anonymous> (test-helpers/https/server.js:9:1794)
      at emitListeningNT (net.js:1288:10)
      at _combinedTickCallback (internal/process/next_tick.js:71:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  6) Update Should work with a provided Data set:
     Uncaught TypeError: Cannot convert undefined or null to object
      at Function.keys (<anonymous>)
      at JSONDeepEquals (src/JSONDeepEquals.js:9:460)
      at CfnLambda (index.js:9:10486)
      at test/update.js:94:7
      at Server.<anonymous> (test-helpers/https/server.js:9:1794)
      at emitListeningNT (net.js:1288:10)
      at _combinedTickCallback (internal/process/next_tick.js:71:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  7) Update Should fail with correct messaging:
     Uncaught TypeError: Cannot convert undefined or null to object
      at Function.keys (<anonymous>)
      at JSONDeepEquals (src/JSONDeepEquals.js:9:460)
      at CfnLambda (index.js:9:10486)
      at test/update.js:200:7
      at Server.<anonymous> (test-helpers/https/server.js:9:1794)
      at emitListeningNT (net.js:1288:10)
      at _combinedTickCallback (internal/process/next_tick.js:71:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)



=============================================================================
Writing coverage object [/Users/robweaver/Projects/cfn-lambda.orig/coverage/coverage.json]
Writing coverage reports at [/Users/robweaver/Projects/cfn-lambda.orig/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 57.67% ( 346/600 )
Branches     : 56.66% ( 183/323 )
Functions    : 53.23% ( 66/124 )
Lines        : 58.05% ( 346/596 )
================================================================================
npm ERR! Test failed.  See above for more details.

```

**Comment by andrew-templeton** [comment]
I'm unable to reproduce any of this unfortunately.
