### ISSUE TITLE
Runtime parameter of nodejs is no longer supported

### ISSUE THREAD

**Issue by whittle** [andrew-templeton/cfn-lambda#14]
I’m attempting to deploy the project https://github.com/mazerte/aws-cloudformation-elastic-transcoder-pipeline using cfn-lambda deploy, and I get the error "InvalidParameterValueException: The runtime parameter of nodejs is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs6.10) while creating or updating functions.". It looks like cfn-lambda is the one specifying the runtime parameter of the AWS Lambda function to create. 

The debug log generated is: 

    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/local/Cellar/node/7.5.0/bin/node',
    1 verbose cli   '/usr/local/bin/npm',
    1 verbose cli   'run',
    1 verbose cli   'cfn-lambda-deploy' ]
    2 info using npm@4.1.2
    3 info using node@v7.5.0
    4 verbose run-script [ 'precfn-lambda-deploy',
    4 verbose run-script   'cfn-lambda-deploy',
    4 verbose run-script   'postcfn-lambda-deploy' ]
    5 info lifecycle aws-cloudformation-elastic-transcoder-pipeline@1.0.0~precfn-lambda-deploy: aws-cloudformation-elastic-transcoder-pipeline@1.0.0
    6 silly lifecycle aws-cloudformation-elastic-transcoder-pipeline@1.0.0~precfn-lambda-deploy: no script for precfn-lambda-deploy, continuing
    7 info lifecycle aws-cloudformation-elastic-transcoder-pipeline@1.0.0~cfn-lambda-deploy: aws-cloudformation-elastic-transcoder-pipeline@1.0.0
    8 verbose lifecycle aws-cloudformation-elastic-transcoder-pipeline@1.0.0~cfn-lambda-deploy: unsafe-perm in lifecycle true
    9 verbose lifecycle aws-cloudformation-elastic-transcoder-pipeline@1.0.0~cfn-lambda-deploy: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/jason/Code/rearc-maltese/vendor/aws-cloudformation-elastic-transcoder-pipeline/node_modules/.bin:/Users/jason/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
    10 verbose lifecycle aws-cloudformation-elastic-transcoder-pipeline@1.0.0~cfn-lambda-deploy: CWD: /Users/jason/Code/rearc-maltese/vendor/aws-cloudformation-elastic-transcoder-pipeline
    11 silly lifecycle aws-cloudformation-elastic-transcoder-pipeline@1.0.0~cfn-lambda-deploy: Args: [ '-c', 'node_modules/cfn-lambda/bin/cfn-lambda deploy' ]
    12 silly lifecycle aws-cloudformation-elastic-transcoder-pipeline@1.0.0~cfn-lambda-deploy: Returned: code: 1  signal: null
    13 info lifecycle aws-cloudformation-elastic-transcoder-pipeline@1.0.0~cfn-lambda-deploy: Failed to exec cfn-lambda-deploy script
    14 verbose stack Error: aws-cloudformation-elastic-transcoder-pipeline@1.0.0 cfn-lambda-deploy: `node_modules/cfn-lambda/bin/cfn-lambda deploy`
    14 verbose stack Exit status 1
    14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
    14 verbose stack     at emitTwo (events.js:106:13)
    14 verbose stack     at EventEmitter.emit (events.js:192:7)
    14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
    14 verbose stack     at emitTwo (events.js:106:13)
    14 verbose stack     at ChildProcess.emit (events.js:192:7)
    14 verbose stack     at maybeClose (internal/child_process.js:890:16)
    14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
    15 verbose pkgid aws-cloudformation-elastic-transcoder-pipeline@1.0.0
    16 verbose cwd /Users/jason/Code/rearc-maltese/vendor/aws-cloudformation-elastic-transcoder-pipeline
    17 error Darwin 15.6.0
    18 error argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "run" "cfn-lambda-deploy"
    19 error node v7.5.0
    20 error npm  v4.1.2
    21 error code ELIFECYCLE
    22 error aws-cloudformation-elastic-transcoder-pipeline@1.0.0 cfn-lambda-deploy: `node_modules/cfn-lambda/bin/cfn-lambda deploy`
    22 error Exit status 1
    23 error Failed at the aws-cloudformation-elastic-transcoder-pipeline@1.0.0 cfn-lambda-deploy script 'node_modules/cfn-lambda/bin/cfn-lambda deploy'.
    23 error Make sure you have the latest version of node.js and npm installed.
    23 error If you do, this is most likely a problem with the aws-cloudformation-elastic-transcoder-pipeline package,
    23 error not with npm itself.
    23 error Tell the author that this fails on your system:
    23 error     node_modules/cfn-lambda/bin/cfn-lambda deploy
    23 error You can get information on how to open an issue for this project with:
    23 error     npm bugs aws-cloudformation-elastic-transcoder-pipeline
    23 error Or if that isn't available, you can get their info via:
    23 error     npm owner ls aws-cloudformation-elastic-transcoder-pipeline
    23 error There is likely additional logging output above.
    24 verbose exit [ 1, true ]

**Comment by whittle** [comment]
Please ignore. Project in question is using a fork of cfn-lambda.
